steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['compile exec:java',
         '-Dexec.mainClass=com.google.cloud.teleport.templates.PubSubToBigQuery',
         '-Dexec.cleanupDaemonThreads=false',
         '-Dexec.args="--project=es-s2dl-core-d --stagingLocation=gs://es-s2dl-core-d-oklev/dataflow/v0.1/staging --tempLocation=gs://es-s2dl-core-d-oklev/dataflow/v0.1/temp --templateLocation=gs://es-s2dl-core-d-oklev/dataflow/v0.1/PubSubToBigQuery --runner=DataflowRunner"'
         ]
